import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-battery-storage-tolling-settlement",
  "engine": "recovery",
  "title": "Battery Storage Tolling Settlement",
  "shortTitle": "Battery Storage Tolling Settlement",
  "tagline": "Calculate tolling revenue, availability payments, efficiency adjustments, dispatch performance, and penalties.",
  "industry": "Energy Storage Finance",
  "buyer": "Battery owners, tolling counterparties, and asset managers",
  "uiPort": 4716,
  "apiPort": 5716,
  "accent": "#b45309",
  "currency": "USD",
  "primaryOutcome": "Battery Storage Tolling Settlement converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements in one accountable workflow. Calculate tolling revenue, availability payments, efficiency adjustments, dispatch performance, and penalties.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Battery Storage Tolling Settlement evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("tolling-agreement-library","BST01","Tolling agreement library","Execute tolling agreement library using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed tolling agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Tolling agreement library Reference","text","BST01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("battery-asset-registry","BST02","Battery asset registry","Execute battery asset registry using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed battery asset registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Battery asset registry Reference","text","BST02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("capacity-commitment","BST03","Capacity commitment","Execute capacity commitment using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed capacity commitment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Capacity commitment Reference","text","BST03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("dispatch-instruction-ingestion","BST04","Dispatch instruction ingestion","Execute dispatch instruction ingestion using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed dispatch instruction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Dispatch instruction ingestion Reference","text","BST04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("telemetry-validation","BST05","Telemetry validation","Execute telemetry validation using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed telemetry validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Telemetry validation Reference","text","BST05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("state-of-charge-reconciliation","BST06","State-of-charge reconciliation","Execute state-of-charge reconciliation using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed state-of-charge reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","State-of-charge reconciliation Reference","text","BST06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("round-trip-efficiency","BST07","Round-trip efficiency","Execute round-trip efficiency using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed round-trip efficiency decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Round-trip efficiency Reference","text","BST07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("availability-calculation","BST08","Availability calculation","Execute availability calculation using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed availability calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Availability calculation Reference","text","BST08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("energy-throughput-calculation","BST09","Energy throughput calculation","Execute energy throughput calculation using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed energy throughput calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Energy throughput calculation Reference","text","BST09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("market-revenue-allocation","BST10","Market revenue allocation","Execute market revenue allocation using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed market revenue allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Market revenue allocation Reference","text","BST10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("performance-penalty-audit","BST11","Performance penalty audit","Execute performance penalty audit using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed performance penalty audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Performance penalty audit Reference","text","BST11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("settlement-statement-matching","BST12","Settlement statement matching","Execute settlement statement matching using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed settlement statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Settlement statement matching Reference","text","BST12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("counterparty-dispute-workflow","BST13","Counterparty dispute workflow","Execute counterparty dispute workflow using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed counterparty dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Counterparty dispute workflow Reference","text","BST13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("cash-reconciliation","BST14","Cash reconciliation","Execute cash reconciliation using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Cash reconciliation Reference","text","BST14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]}),
feature("asset-market-analytics","BST15","Asset market analytics","Execute asset market analytics using tolling agreements, capacity commitments, dispatch instructions, telemetry, state of charge, availability, efficiency, market revenue, penalties, invoices, and settlements.","Produce a governed asset market analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Battery / Tolling Agreement","text","Battery / Tolling Agreement · Standard Case"],["caseReference","Asset market analytics Reference","text","BST15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1511250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1828613],["domainDriver","Revenue Stream","select","Capacity",["Capacity","Energy arbitrage","Ancillary service"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Tolling agreement library case","Battery asset registry case","Capacity commitment case","Dispatch instruction ingestion case","Telemetry validation case"]})
]);
